import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import fc from 'fast-check'
import type { Hex } from 'viem'
import { describe, expect, it } from 'vitest'

import { encodeAttribution, parseAttribution } from '../../src/attribution'
import { isSnfError } from '../../src/errors'

/**
 * ERC-8021 schema-0 encode/parse against the shared vector file. The file is shared
 * byte-for-byte with every other reader of the format: its valid `suffix` fields were
 * generated by `ox/erc8021`'s `Attribution.toDataSuffix`, so `encodeAttribution`
 * matching them proves byte-identity with `ox` without depending on it.
 */

interface ValidVector {
  readonly name: string
  readonly data: Hex
  readonly suffix?: Hex
  readonly expected: readonly string[]
}
interface InvalidVector {
  readonly name: string
  readonly data: Hex
  readonly expected: null
}
interface VectorFile {
  readonly marker: Hex
  readonly valid: readonly ValidVector[]
  readonly invalid: readonly InvalidVector[]
}

const HERE = dirname(fileURLToPath(import.meta.url))
const VECTORS = JSON.parse(
  readFileSync(resolve(HERE, '../fixtures/attribution/attribution-vectors.json'), 'utf8'),
) as VectorFile

function expectInvalidParams(fn: () => unknown): void {
  try {
    fn()
  } catch (e) {
    expect(isSnfError(e) && e.code).toBe('INVALID_PARAMS')
    return
  }
  throw new Error('expected INVALID_PARAMS to be thrown')
}

describe('attribution vectors', () => {
  it('has the expected shape (9 valid, 13 invalid)', () => {
    expect(VECTORS.valid).toHaveLength(9)
    expect(VECTORS.invalid).toHaveLength(13)
    expect(VECTORS.marker).toBe('0x80218021802180218021802180218021')
  })

  it.each(VECTORS.valid.map((v) => [v.name, v] as const))('parses valid vector: %s', (_name, vector) => {
    expect(parseAttribution(vector.data)).toEqual(vector.expected)
  })

  it.each(VECTORS.invalid.map((v) => [v.name, v] as const))('rejects invalid vector: %s', (_name, vector) => {
    expect(parseAttribution(vector.data)).toBeNull()
  })

  const withSuffix = VECTORS.valid.filter((v): v is ValidVector & { suffix: Hex } => v.suffix !== undefined)

  it('covers at least the ox-generated vectors', () => {
    expect(withSuffix.length).toBeGreaterThanOrEqual(6)
  })

  it.each(withSuffix.map((v) => [v.name, v] as const))(
    'encodes byte-identically to the ox-generated suffix: %s',
    (_name, vector) => {
      expect(encodeAttribution(vector.expected)).toBe(vector.suffix)
      // And the vector's calldata is exactly the selector/args followed by that suffix.
      expect(vector.data.endsWith(vector.suffix.slice(2))).toBe(true)
    },
  )
})

describe('encodeAttribution', () => {
  it('reproduces the reference vector for ["baseapp", "morpho"]', () => {
    expect(encodeAttribution(['baseapp', 'morpho'])).toBe(
      '0x626173656170702c6d6f7270686f0e0080218021802180218021802180218021',
    )
  })

  it('rejects an empty list, an empty code, a comma, a space, a control byte and non-ASCII', () => {
    expectInvalidParams(() => encodeAttribution([]))
    expectInvalidParams(() => encodeAttribution(['']))
    expectInvalidParams(() => encodeAttribution(['a,b']))
    expectInvalidParams(() => encodeAttribution(['a b']))
    expectInvalidParams(() => encodeAttribution(['a\nb']))
    expectInvalidParams(() => encodeAttribution(['café']))
  })

  it('accepts exactly 255 comma-joined bytes and rejects 256', () => {
    expect(parseAttribution(`0xa9059cbb${encodeAttribution(['a'.repeat(255)]).slice(2)}`)).toEqual(['a'.repeat(255)])
    expectInvalidParams(() => encodeAttribution(['a'.repeat(256)]))
    expectInvalidParams(() => encodeAttribution(['a'.repeat(128), 'b'.repeat(127)]))
  })
})

describe('parseAttribution', () => {
  it('returns null (never throws) for malformed hex', () => {
    expect(parseAttribution('0x0' as Hex)).toBeNull()
    expect(parseAttribution('0xzz' as Hex)).toBeNull()
    expect(parseAttribution('nothex' as Hex)).toBeNull()
  })

  it('property: encode then parse round-trips any list of lowercase codes (after a selector)', () => {
    const code = fc.stringMatching(/^[a-z0-9][a-z0-9-]{0,31}$/)
    fc.assert(
      fc.property(fc.array(code, { minLength: 1, maxLength: 4 }), fc.uint8Array({ maxLength: 64 }), (codes, args) => {
        const argsHex = Array.from(args, (b) => b.toString(16).padStart(2, '0')).join('')
        const data = `0xa9059cbb${argsHex}${encodeAttribution(codes).slice(2)}` as Hex
        expect(parseAttribution(data)).toEqual(codes)
      }),
      { numRuns: 200 },
    )
  })
})
